activation: silu
aggr: add
atom_filter: -1
attn_activation: silu
batch_size: 8
charge: false
coord_files: null
cutoff_lower: 0.0
cutoff_upper: 5.0
#dataset: MD17 # remove later
#dataset_arg:  # remove later
#  molecules: aspirin  # remove later
dataset_root: /home/civil/btech/ce1180169/MDBENCHGNN/example/lips20/data/
derivative: true
distance_influence: both
early_stopping_patience: 300
ema_alpha_neg_dy: 1.0
ema_alpha_y: 0.05
embed_files: null
embedding_dimension: 128
energy_files: null
y_weight: 0.5
force_files: null
neg_dy_weight: 0.5
inference_batch_size: 8
load_model: null
log_dir: /home/civil/btech/ce1180169/MDBENCHGNN/output_dir_sl/tmdnet/lips20/
lr: 0.001
lr_factor: 0.8
lr_min: 1.0e-07
lr_patience: 30
lr_warmup_steps: 1000
max_z: 100
model: equivariant-transformer
neighbor_embedding: true
ngpus: -1
num_epochs: 5000
num_heads: 8
num_layers: 6
num_nodes: 1
num_rbf: 32
num_workers: 6
output_model: Scalar
precision: 32
prior_model: null
rbf_type: expnorm
redirect: false
reduce_op: add
save_interval: 10
splits: null
standardize: true
test_interval: 10
test_size: null
train_size: 900
trainable_rbf: false
val_size: 100
weight_decay: 0.0
data_format: xyz
energy_key: energy # dataset
forces_key: forces # dataset
positions_key: pos # dataset
atomic_num_key: atomic_numbers # dataset
max_num_neighbors: 50 #Maximum no. of neighbors
